### ISSUE TITLE
会議ツール

### ISSUE THREAD

**Issue by uub** [gamedevja/gamedevja.github.io#2]

**Comment by uub** [comment]
Katoはいかがでしょう。
# 招待
http://go.kato.im/UKGcOdhg
上記より[Kato](https://kato.im/)のgamdevjチームにアクセスできます。
# なぜKatoか
私はこれまでSlackを使っていましたが、自動招待に外部サーバーを使わなければならないという問題がありました。Katoは上記の通り、URL一発です。機能的にも素晴らしいです。SlackにあってKatoに無いものは包括的なAPIとデスクトップネイティブアプリくらいです。
# できること
必要なものはだいたい。

**Comment by kurehajime** [comment]
リアルタイムな会議ツールとは別枠で議論した方が良いのかも知れませんが、個人的には「プロジェクトに加入する前にROM専でプロジェクトの様子が覗ける」という体制が構築出来れば良いなぁ、と思います。

メンバー限定のツールを使う場合でも、ログが残せて極力オープンにできるような。

**Comment by uub** [comment]
とりあえずgitterルーム作っておきました。
